services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mysql_recommendation
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: resource_recommendation
      MYSQL_PASSWORD: 12345678
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # 后端服务
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: recommendation_backend
    restart: unless-stopped
    ports:
      - "8082:8000"
    environment:
      # 应用基础配置
      - APP_NAME=Resource Recommendation API
      - APP_VERSION=1.0.0
      - DEBUG=false
      - ENVIRONMENT=docker
      # 服务器配置
      - HOST=0.0.0.0
      - PORT=8000
      # MySQL数据库配置
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=resource_recommendation
      - MYSQL_CHARSET=utf8mb4
      # 日志配置
      - LOG_LEVEL=INFO
      - LOG_FILE=./logs/app.log
      # 其他配置
      - PYTHONPATH=/app
      - DATABASE_URL_ENV=mysql+asyncmy://appuser:apppassword@mysql:3306/resource_recommendation
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge