version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mysql_recommendation
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: resource_recommendation
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommendation_backend
    restart: unless-stopped
    ports:
      - "8082:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppassword@mysql:13306/resource_recommendation
      - ENVIRONMENT=docker
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logs
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge